RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/txt_db/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=txt_db.h

O_OBJS=txt_db.o

include $(RGMK)
include $(SSLMK)
