O_TARGET := digests.o

obj-$(CONFIG_DIGEST_MD5)      += digest-md5.o
obj-$(CONFIG_DIGEST_SHA1)     += digest-sha1.o
obj-$(CONFIG_DIGEST_RIPEMD160)+= digest-ripemd160.o
obj-$(CONFIG_DIGEST_SHA256)   += digest-sha256.o
obj-$(CONFIG_DIGEST_SHA384)   += digest-sha384.o
obj-$(CONFIG_DIGEST_SHA512)   += digest-sha512.o

include $(TOPDIR)/Rules.make
