RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/conf/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=conf.h conf_api.h

O_OBJS=conf_err.o conf_lib.o conf_api.o conf_def.o

include $(RGMK)
include $(SSLMK)
