RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/lhash/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=lhash.h

O_OBJS=lhash.o lh_stats.o

include $(RGMK)
include $(SSLMK)
