RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/buffer/Makefile
#

TOP=	../..

CREATE_LIB=y

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=buffer.h

O_OBJS= buffer.o buf_err.o

include $(RGMK)
include $(SSLMK)
