O_TARGET := ciphers.o

obj-$(CONFIG_CIPHER_AES)      += cipher-aes.o
obj-$(CONFIG_CIPHER_BLOWFISH) += cipher-blowfish.o
obj-$(CONFIG_CIPHER_BLOWFISH_OLD) += cipher-blowfish_old.o
obj-$(CONFIG_CIPHER_CAST5)    += cipher-cast5.o
obj-$(CONFIG_CIPHER_DES)      += cipher-des.o
obj-$(CONFIG_CIPHER_3DES)     += cipher-3des.o
obj-$(CONFIG_CIPHER_DFC)      += cipher-dfc.o
obj-$(CONFIG_CIPHER_IDEA)     += cipher-idea.o
obj-$(CONFIG_CIPHER_MARS)     += cipher-mars.o
obj-$(CONFIG_CIPHER_RC5)      += cipher-rc5.o
obj-$(CONFIG_CIPHER_RC6)      += cipher-rc6.o
obj-$(CONFIG_CIPHER_SERPENT)  += cipher-serpent.o
obj-$(CONFIG_CIPHER_TWOFISH)  += cipher-twofish.o
obj-$(CONFIG_CIPHER_NULL)     += cipher-null.o
obj-$(CONFIG_CIPHER_DUMMY)    += cipher-dummy.o

include $(TOPDIR)/Rules.make
