TOPDIR=../../
include $(TOPDIR)Rules.mak

A_TARGET=$(LIBC)

O_OBJS_$(LIBC)=allocrtsig.o killpg.o raise.o sigaction.o sigaddset.o \
  sigandset.o sigblock.o sigdelset.o sigempty.o sigfillset.o siggetmask.o \
  sighold.o sigignore.o sigintr.o sigisempty.o sigismem.o sigjmp.o signal.o \
  sigorset.o sigpause.o sigrelse.o sigset.o sigsetmask.o sigsetops.o \
  sysv_signal.o

include $(RGMK)

