RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/err/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=err.h

O_OBJS=err.o err_all.o err_prn.o

include $(RGMK)
include $(SSLMK)
