RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/pem/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=pem.h pem2.h

O_OBJS=pem_sign.o pem_seal.o pem_info.o pem_lib.o pem_all.o pem_err.o

include $(RGMK)
include $(SSLMK)
