RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/stack/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=stack.h safestack.h

O_OBJS=stack.o


include $(RGMK)
include $(SSLMK)
