TOPDIR=../../../
include $(TOPDIR)Rules.mak

A_TARGET=$(LIBC)

# calloc.c can be found at uClibc/libc/stdlib/calloc.c 
# valloc.c can be found at uClibc/libc/stdlib/valloc.c 
O_OBJS_$(LIBC)=malloc.o memalign.o realloc.o

include $(RGMK)

