TOPDIR=../../../
include $(TOPDIR)Rules.mak

A_TARGET=$(LIBC)

O_OBJS_$(LIBC)=alphasort.o closedir.o dirfd.o opendir.o readdir.o rewinddir.o \
  scandir.o seekdir.o telldir.o readdir64.o alphasort64.o scandir64.o \
  readdir_r.o readdir64_r.o

include $(RGMK)

