RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/comp/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=
APPS=
EXPORT_HEADERS=comp.h

O_OBJS=comp_lib.o comp_err.o c_rle.o c_zlib.o

include $(RGMK)
include $(SSLMK)
