RGSRC=../../../../
include $(RGSRC)/envir.mak
#
# SSLeay/crypto/md/Makefile
#

TOP=	../..

include ../crypto_env.mak

TEST=hmactest.c
APPS=

EXPORT_HEADERS=hmac.h

O_OBJS=hmac.o

include $(RGMK)

include $(SSLMK)

